### ISSUE TITLE
Unable to train NER using custom ELMO embedding model

### ISSUE THREAD

**Issue by sathiyabalu89** [kermitt2/delft#113]
I have trained my own Chemical based ELMO embedding model. I have used default options for training elmo expect the "max_characters_per_token": 25 (default value is 50). I have both the hdf5 file and option file. This is how my options.json looks like.

`"{"bidirectional": true, "char_cnn": {"activation": "relu", "embedding": {"dim": 16}, "filters": [[1, 32], [2, 32], [3, 64], [4, 128], [5, 256], [6, 512], [7, 1024]], "max_characters_per_token": 25, "n_characters": 262, "n_highway": 2}, "dropout": 0.1, "lstm": {"cell_clip": 3, "dim": 4096, "n_layers": 2, "proj_clip": 3, "projection_dim": 512, "use_skip_connections": true}, "all_clip_norm_val": 10.0, "n_epochs": 10, "n_train_tokens": 684095660, "batch_size": 256, "n_tokens_vocab": 6426860, "unroll_steps": 20, "n_negative_samples_batch": 8192}"`

When I try to run the command "python nerTagger.py --architecture BidLSTM_CNN_CRF --use-ELMo --embedding word2vec train" I get the following error. However if I try with default ELMO model, training completes successfully. 

```
>>python nerTagger.py --architecture BidLSTM_CNN_CRF --use-ELMo --embedding word2vec train

Using TensorFlow backend.
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From /home/developer/deep_learning/workspace/NLP_PROJECTS/CAS_POC_NER/delft/delft-master/delft/sequenceLabelling/preprocess.py:24: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

WARNING:tensorflow:From /home/developer/deep_learning/workspace/NLP_PROJECTS/CAS_POC_NER/delft/delft-master/delft/utilities/bert/optimization.py:87: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Loading data...
/home/developer/.local/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)
5 train sequences
         nb. tokens 31
         with nb. entities 13
1 validation sequences
         nb. tokens 2
         with nb. entities 2


6 total sequences
33 total tokens

total distinct characters: 23 

init ELMo
WARNING:tensorflow:From /home/developer/deep_learning/workspace/NLP_PROJECTS/CAS_POC_NER/delft/delft-master/delft/utilities/Embeddings.py:352: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/developer/deep_learning/workspace/NLP_PROJECTS/CAS_POC_NER/delft/delft-master/delft/utilities/Embeddings.py:354: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/developer/deep_learning/workspace/NLP_PROJECTS/CAS_POC_NER/delft/delft-master/delft/utilities/Embeddings.py:354: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.

WARNING:tensorflow:From /home/developer/deep_learning/workspace/NLP_PROJECTS/CAS_POC_NER/delft/delft-master/delft/utilities/bilm/model.py:332: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From /home/developer/deep_learning/workspace/NLP_PROJECTS/CAS_POC_NER/delft/delft-master/delft/utilities/bilm/model.py:377: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

WARNING:tensorflow:From /opt/conda/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:180: calling squeeze (from tensorflow.python.ops.array_ops) with squeeze_dims is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1864, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Can not squeeze dim[2], expected a dimension of 1, got 26 for 'en/bilm/CNN/Squeeze' (op: 'Squeeze') with input shapes: [?,?,26,32].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nerTagger.py", line 603, in <module>
    data_path=data_path)
  File "nerTagger.py", line 63, in train
    use_BERT=use_BERT)
  File "/home/developer/deep_learning/workspace/NLP_PROJECTS/CAS_POC_NER/delft/delft-master/delft/sequenceLabelling/wrapper.py", line 95, in __init__
    self.embeddings = Embeddings(embeddings_name, use_ELMo=use_ELMo, use_BERT=use_BERT)
  File "/home/developer/deep_learning/workspace/NLP_PROJECTS/CAS_POC_NER/delft/delft-master/delft/utilities/Embeddings.py", line 88, in __init__
    self.make_ELMo()
  File "/home/developer/deep_learning/workspace/NLP_PROJECTS/CAS_POC_NER/delft/delft-master/delft/utilities/Embeddings.py", line 356, in make_ELMo
    self.embeddings_op = self.bilm(self.character_ids)
  File "/home/developer/deep_learning/workspace/NLP_PROJECTS/CAS_POC_NER/delft/delft-master/delft/utilities/bilm/model.py", line 99, in __call__
    max_batch_size=self._max_batch_size)
  File "/home/developer/deep_learning/workspace/NLP_PROJECTS/CAS_POC_NER/delft/delft-master/delft/utilities/bilm/model.py", line 280, in __init__
    self._build()
  File "/home/developer/deep_learning/workspace/NLP_PROJECTS/CAS_POC_NER/delft/delft-master/delft/utilities/bilm/model.py", line 284, in _build
    self._build_word_char_embeddings()
  File "/home/developer/deep_learning/workspace/NLP_PROJECTS/CAS_POC_NER/delft/delft-master/delft/utilities/bilm/model.py", line 389, in _build_word_char_embeddings
    embedding = make_convolutions(self.char_embedding)
  File "/home/developer/deep_learning/workspace/NLP_PROJECTS/CAS_POC_NER/delft/delft-master/delft/utilities/bilm/model.py", line 383, in make_convolutions
    conv = tf.squeeze(conv, squeeze_dims=[2])
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 3162, in squeeze
    return gen_array_ops.squeeze(input, axis, name)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 9666, in squeeze
    "Squeeze", input=input, squeeze_dims=axis, name=name)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2027, in __init__
    control_input_ops)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1867, in _create_c_op
    raise ValueError(str(e))
ValueError: Can not squeeze dim[2], expected a dimension of 1, got 26 for 'en/bilm/CNN/Squeeze' (op: 'Squeeze') with input shapes: [?,?,26,32].
```

 Also just to verify whether "max_characters_per_token": 25 is creating error, I tried changing "max_characters_per_token": 25 to 50 in options.json file and train completed fully. So somewhere inside the code, "max_characters_per_token=50" is hardcoded. But unable to find the exact location.

Please note that all library versions are in line with requirement.txt. Any help is greatly appreciated.

**Comment by sathiyabalu89** [comment]
In embedding.py, make_elmo() function, in line no. 346 and 352, the max character length of 50 is hard coded. I changed it to 25 and the below error is rectified.
