### ISSUE TITLE
sequenceLabelling ValueError

### ISSUE THREAD

**Issue by YuhwaChoong** [kermitt2/delft#13]
I'm testing the tag function of sequenceLabelling models on Windows 10, and I met ValueErrors for all models. I didn't change any code inside and only ran the code:

> def tag_line(text):
>     # load model
>     model_name = 'ner-en-conll2003-BidGRU_CRF'
>     model = sequenceLabelling.Sequence(model_name)
>     model.load()
>     results = model.tag(text, "json")
>     return results
> 
> if __name__ == "__main__":
>     text = ["Trump lives in New York"]
>     tag_line(text)

The detailed error messages are as below.

```
loading model weights data/models/sequenceLabelling/ner-en-conll2003-BidGRU_CRF\model_weights.hdf5
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 50 and 350. Shapes are [50,300] and [350,300]. for 'Assign_7' (op: 'Assign') with input shapes: [50,300], [350,300].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/YuhwaChoong/Desktop/Delft/delft/nerTagger.py", line 476, in <module>
    tag_line(text)
  File "C:/Users/YuhwaChoong/Desktop/Delft/delft/nerTagger.py", line 470, in tag_line
    model.load()
  File "C:\Users\YuhwaChoong\Desktop\Delft\delft\sequenceLabelling\wrapper.py", line 366, in load
    self.model.load(filepath=os.path.join(dir_path, self.model_config.model_name, self.weight_file))
  File "C:\Users\YuhwaChoong\Desktop\Delft\delft\sequenceLabelling\models.py", line 60, in load
    self.model.load_weights(filepath=filepath)
  File "D:\Anaconda\lib\site-packages\keras\engine\topology.py", line 2656, in load_weights
    f, self.layers, reshape=reshape)
  File "D:\Anaconda\lib\site-packages\keras\engine\topology.py", line 3382, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "D:\Anaconda\lib\site-packages\keras\backend\tensorflow_backend.py", line 2368, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\ops\variables.py", line 609, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\ops\state_ops.py", line 281, in assign
    validate_shape=validate_shape)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 3292, in create_op
    compute_device=compute_device)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 3332, in _create_op_helper
    set_shapes_for_outputs(op)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 2496, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 2469, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 2399, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 0 in both shapes must be equal, but are 50 and 350. Shapes are [50,300] and [350,300]. for 'Assign_7' (op: 'Assign') with input shapes: [50,300], [350,300].
```

**Comment by kermitt2** [comment]
Hello @YuhwaChoong !

It's simply that the embeddings are missing. On the first time, the embeddings will be compiled in a LDMB database so that next launch will be immediate without loading embeddings into memory.  

If, for some reason, the initial embeddings loading failed, you need to delete the empty db:

> rm -rf delft/data/db/glove-840B

and relaunch so that the LMDB is rebuilt.

Be sure that the path to the Glove embedding file is correct in `embedding-registry.json` and that you have correctly downloaded the glove embedding file 300d http://nlp.stanford.edu/data/glove.840B.300d.zip before the first launch - the sequence labelling models all use these Glove embeddings. 

You should get this message:

```
Compiling embeddings... (this is done only one time per embeddings at first launch)
path: /home/lopez/embeddings/glove.840B.300d.txt
100%|█████████████████████████████████| 2196017/2196017 [06:47<00:00, 5388.91it/s]
embeddings loaded for 2196006 words and 300 dimensions
```

and then the tagging should be fine:

```
loading model weights data/models/sequenceLabelling/ner-en-conll2003-BidGRU_CRF/model_weights.hdf5
{
    "model": "ner-en-conll2003-BidGRU_CRF",
    "runtime": 0.364,
    "software": "DeLFT",
    "date": "2018-09-19T10:58:05.754971",
    "texts": [
        {
            "entities": [
                {
                    "score": 1.0,
                    "class": "PER",
                    "text": "Trump",
                    "beginOffset": 0,
                    "endOffset": 4
                },
                {
                    "score": 1.0,
                    "class": "LOC",
                    "text": "New York",
                    "beginOffset": 15,
                    "endOffset": 22
                }
            ],
            "text": "Trump lives in New York"
        }
    ]
}
runtime: 0.365 seconds 
```

I will try to make the embeddings loading process more robust and the error messages more clear.

**Comment by YuhwaChoong** [comment]
Hello @kermitt2. So much thanks for your answer! 
I found out that the first build of LDMB failed and the failed db file ocupied 100GB disk space. 
I thought the reason why the build process failed in my PC is that default encoding of my OS is gbk, not utf8, and the code
           `with open(embeddings_path) as f:`
in file Embeddings.py line 159 and line 163 used the OS default encoding to open the glove files. This could be fixed to change the line into:
           `with open(embeddings_path,encoding='utf8') as f:`

**Comment by kermitt2** [comment]
Thanks a lot ! I have updated the file `Embeddings.py` as you suggested.
