### ISSUE TITLE
Batch-size=1

### ISSUE THREAD

**Issue by HaniehP** [kermitt2/delft#19]
Hi,
When I set batch_size=1, I got the following error:

Traceback (most recent call last):
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnimplementedError: TensorArray has size zero, but element shape [?,10] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: chain_crf_1/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@chain_crf_1/TensorArray"], dtype=DT_FLOAT, element_shape=[?,10], _device="/job:localhost/replica:0/task:0/device:GPU:0"](chain_crf_1/TensorArray, chain_crf_1/TensorArrayStack/range, chain_crf_1/while/Exit_1)]]
	 [[Node: chain_crf_1/while_1/Reshape_1/_321 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2949_chain_crf_1/while_1/Reshape_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopchain_crf_1/while_1/TensorArrayReadV3/_267)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nerTagger.py", line 440, in <module>
    data_path=data_path)
  File "nerTagger.py", line 271, in train_eval
    model.train(x_train, y_train, x_valid, y_valid)
  File "/data/hpoostch/PycharmProjects/ELMo_Lample/CrossEntropy/delft-master/sequenceLabelling/wrapper.py", line 130, in train
    trainer.train(x_train, y_train, x_valid, y_valid)
  File "/data/hpoostch/PycharmProjects/ELMo_Lample/CrossEntropy/delft-master/sequenceLabelling/trainer.py", line 61, in train
    self.training_config.max_epoch)
  File "/data/hpoostch/PycharmProjects/ELMo_Lample/CrossEntropy/delft-master/sequenceLabelling/trainer.py", line 101, in train_model
    callbacks=callbacks)
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/keras/engine/training.py", line 2224, in fit_generator
    class_weight=class_weight)
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/keras/engine/training.py", line 1883, in train_on_batch
    outputs = self.train_function(ins)
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2478, in __call__
    **self.session_kwargs)
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: TensorArray has size zero, but element shape [?,10] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: chain_crf_1/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@chain_crf_1/TensorArray"], dtype=DT_FLOAT, element_shape=[?,10], _device="/job:localhost/replica:0/task:0/device:GPU:0"](chain_crf_1/TensorArray, chain_crf_1/TensorArrayStack/range, chain_crf_1/while/Exit_1)]]
	 [[Node: chain_crf_1/while_1/Reshape_1/_321 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2949_chain_crf_1/while_1/Reshape_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopchain_crf_1/while_1/TensorArrayReadV3/_267)]]

Caused by op 'chain_crf_1/TensorArrayStack/TensorArrayGatherV3', defined at:
  File "nerTagger.py", line 440, in <module>
    data_path=data_path)
  File "nerTagger.py", line 271, in train_eval
    model.train(x_train, y_train, x_valid, y_valid)
  File "/data/hpoostch/PycharmProjects/ELMo_Lample/CrossEntropy/delft-master/sequenceLabelling/wrapper.py", line 121, in train
    self.model = get_model(self.model_config, self.p, len(self.p.vocab_tag))
  File "/data/hpoostch/PycharmProjects/ELMo_Lample/CrossEntropy/delft-master/sequenceLabelling/models.py", line 19, in get_model
    return BidLSTM_CRF(config, ntags)
  File "/data/hpoostch/PycharmProjects/ELMo_Lample/CrossEntropy/delft-master/sequenceLabelling/models.py", line 112, in __init__
    pred = self.crf(x)
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/data/hpoostch/PycharmProjects/ELMo_Lample/CrossEntropy/delft-master/utilities/layers.py", line 313, in call
    y_pred = viterbi_decode(x, self.U, self.b_start, self.b_end, mask)
  File "/data/hpoostch/PycharmProjects/ELMo_Lample/CrossEntropy/delft-master/utilities/layers.py", line 105, in viterbi_decode
    mask)
  File "/data/hpoostch/PycharmProjects/ELMo_Lample/CrossEntropy/delft-master/utilities/layers.py", line 146, in _forward
    last, values, _ = K.rnn(_forward_step, inputs, initial_states)
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2772, in rnn
    outputs = output_ta.stack()
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 893, in stack
    return self._implementation.stack(name=name)
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 291, in stack
    return self.gather(math_ops.range(0, self.size()), name=name)
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 305, in gather
    element_shape=element_shape)
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 6011, in tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/data/hpoostch/py3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,10] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: chain_crf_1/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@chain_crf_1/TensorArray"], dtype=DT_FLOAT, element_shape=[?,10], _device="/job:localhost/replica:0/task:0/device:GPU:0"](chain_crf_1/TensorArray, chain_crf_1/TensorArrayStack/range, chain_crf_1/while/Exit_1)]]
	 [[Node: chain_crf_1/while_1/Reshape_1/_321 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2949_chain_crf_1/while_1/Reshape_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopchain_crf_1/while_1/TensorArrayReadV3/_267)]]

**Comment by letiantony** [comment]
Hi, I had the same problem when I use Elmo with delft.  The solution is to  delete all sentences from the labeled data which length is 1. FYI , It worked for me .

**Comment by kermitt2** [comment]
Hello! Thanks, this is a problem with TensorFlow `tf.map_fn()`, we need to prevent that only sequences of length 1 appears in a batch when padding the sequence. Fixed with 00ce25b5a77a8d66ef358d8d35c1648037a73b6d (without deletion!).
